// The session shape and every legal mutation of it.
//
// Two invariants the rest of the app depends on:
//   1. Nothing outside this file mutates a session. Every reducer returns a NEW
//      object with `rev + 1`, so an accidental in-place mutation is detectable and a
//      future reconciliation has a version to compare. Nothing reads `rev` yet:
//      saveSession does an unconditional put, and two tabs on one session are still
//      last-write-wins with no merge. It is a mutation counter today, not a mechanism —
//      see docs/ARCHITECTURE.md for what building the real thing would cost.
//   2. No timestamps or randomness reach anything the prompt builder reads.
//      Prompt construction must be a pure function of session state so an
//      interrupted call can be replayed from cache for free (see engine.promptHash).

import { DIMENSIONS, DIMENSION_IDS, LEVEL_RANK, getDimension } from './dimensions.js';

export const SCHEMA = 1;

/** Coverage may rise at most one level per dimension per turn... */
const MAX_LEVEL_RISE_PER_TURN = 1;
/** ...and at most this many dimensions may rise in any single turn. */
const MAX_DIMENSIONS_RISING_PER_TURN = 2;

const isRecord = (value) => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const recordArray = (value) => Array.isArray(value) ? value.filter(isRecord) : [];

export function createSession({ id, now = 0, device = 'desktop' } = {}) {
  if (!id) throw new Error('createSession requires an id (generated by the caller, not core)');
  const coverage = {};
  for (const d of DIMENSIONS) {
    coverage[d.id] = {
      level: 'thin', status: 'probing', gap: null, evidence: null,
      turnsSpent: 0, lastTurn: 0, waivedReason: null,
    };
  }
  return {
    schema: SCHEMA,
    id,
    rev: 0,
    createdAt: now,
    updatedAt: now,
    status: 'interviewing',        // interviewing | synthesizing | done
    title: '',
    opening: '',                   // the user's verbatim opening statement
    turns: [],
    coverage,
    facts: [],                     // [{dimension, fact}] — the compaction ledger
    moveHistory: [],
    openQuestions: [],
    synthesis: { text: '', tier: '', at: 0, stale: false, assumptions: [] },
    draftAnswer: '',
    pending: null,                 // {kind, turnId, promptHash, startedAt}
    zeroGainStreak: 0,
    wrapOffered: false,
    meta: { device },
  };
}

function bump(session, patch, now) {
  return {
    ...session, ...patch,
    rev: session.rev + 1,
    updatedAt: now == null ? session.updatedAt : now,
  };
}

/** Record a question that has been put to the user. */
export function askQuestion(session, { question, dimension, move = null, chips = [], bridge = null, source = 'model', now = 0 }) {
  if (!question) throw new Error('askQuestion requires a question');
  const n = session.turns.length + 1;
  const turn = {
    id: `t${n}`, n, dimension, question, bridge, move, chips,
    questionSource: source,
    answer: '', answerSource: null, draftText: null,
    skipped: false, askedAt: now, answeredAt: 0, classification: null,
  };
  const patch = { turns: [...session.turns, turn] };
  if (move) patch.moveHistory = [...session.moveHistory, move];
  if (dimension && session.coverage[dimension]) {
    patch.coverage = {
      ...session.coverage,
      [dimension]: {
        ...session.coverage[dimension],
        turnsSpent: session.coverage[dimension].turnsSpent + 1,
        lastTurn: n,
      },
    };
  }
  return bump(session, patch, now);
}

/**
 * Record the user's answer to the open turn.
 * `source` drives the provenance discount: chip and draft-unedited answers are
 * Claude's words, not the user's, and must never take a dimension to `covered`.
 */
export function answerQuestion(session, { text, source = 'typed', classification = null, now = 0 }) {
  const idx = session.turns.length - 1;
  if (idx < 0) throw new Error('no open turn to answer');
  const turns = session.turns.slice();
  const open = turns[idx];
  let resolvedSource = source;
  if (source === 'draft') {
    resolvedSource = open.draftText != null && open.draftText === text
      ? 'draft-unedited' : 'draft-edited';
  }
  turns[idx] = { ...open, answer: text, answerSource: resolvedSource, answeredAt: now, classification };
  const patch = { turns, draftAnswer: '' };
  if (open.n === 1 && !session.opening) patch.opening = text;
  return bump(session, patch, now);
}

/**
 * The user declined to answer. `skipped` is structurally distinct from an answer whose
 * text reads "(skipped)", which is how this was once faked: `openTurn`, `serializeTurn`
 * and the export all branch on the flag, and none of them can read intent out of prose.
 */
export function skipQuestion(session, { now = 0 } = {}) {
  const idx = session.turns.length - 1;
  if (idx < 0) throw new Error('no open turn to skip');
  const turns = session.turns.slice();
  // Same notion of "open" as openTurn: an answered OR already-skipped turn is closed.
  if (turns[idx].answer || turns[idx].skipped) throw new Error('no open turn to skip');
  turns[idx] = { ...turns[idx], skipped: true, answeredAt: now, classification: 'refusal' };
  return bump(session, { turns, draftAnswer: '' }, now);
}

export function setDraftText(session, text, now = 0) {
  const idx = session.turns.length - 1;
  if (idx < 0) return session;
  const turns = session.turns.slice();
  turns[idx] = { ...turns[idx], draftText: text };
  return bump(session, { turns, draftAnswer: text }, now);
}

export function setDraftAnswer(session, text, now = 0) {
  return bump(session, { draftAnswer: text }, now);
}

/** True when this answer's provenance means it cannot support a `covered` grade. */
export function isLowConfidence(turn) {
  return turn.answerSource === 'chip' || turn.answerSource === 'draft-unedited';
}

/**
 * Apply a parsed turn result, clamping the model's coverage claims.
 *
 * The model self-reports coverage in-band (zero extra calls), and self-reported
 * coverage drifts optimistic. The ratchet is the structural defense: coverage
 * never falls silently, never leaps more than one level, and never more than two
 * dimensions at a time.
 */
export function applyCoverage(session, claimed, { lowConfidenceDimension = null, cappedDimensions = [], now = 0 } = {}) {
  const next = {};
  const risen = [];

  for (const id of DIMENSION_IDS) {
    const cur = session.coverage[id];
    const claim = claimed && claimed[id];
    if (!claim || cur.status !== 'probing') { next[id] = cur; continue; }

    let level = LEVELS_HAS(claim.level) ? claim.level : cur.level;

    // Provenance + dodge caps: never better than `partial`.
    if ((lowConfidenceDimension === id || cappedDimensions.includes(id)) && level === 'covered') {
      level = 'partial';
    }
    // Evidence requirement: `covered` without a user quote is not covered.
    if (level === 'covered' && !nonEmpty(claim.evidence)) level = 'partial';

    // Ratchet: never decrease, never rise more than one level.
    if (LEVEL_RANK[level] < LEVEL_RANK[cur.level]) level = cur.level;
    if (LEVEL_RANK[level] - LEVEL_RANK[cur.level] > MAX_LEVEL_RISE_PER_TURN) {
      level = LEVELS_AT(LEVEL_RANK[cur.level] + MAX_LEVEL_RISE_PER_TURN);
    }
    if (LEVEL_RANK[level] > LEVEL_RANK[cur.level]) risen.push(id);

    next[id] = {
      ...cur,
      level,
      gap: level === 'covered' ? null : (nonEmpty(claim.gap) ? claim.gap : cur.gap),
      evidence: level === 'covered' ? claim.evidence : cur.evidence,
    };
  }

  // Cap the number of dimensions allowed to rise: keep the most defensible.
  if (risen.length > MAX_DIMENSIONS_RISING_PER_TURN) {
    const keep = new Set(risen.slice(0, MAX_DIMENSIONS_RISING_PER_TURN));
    for (const id of risen) {
      if (!keep.has(id)) next[id] = { ...next[id], level: session.coverage[id].level };
    }
  }
  return bump(session, { coverage: next }, now);
}

const LEVELS_HAS = (l) => l === 'thin' || l === 'partial' || l === 'covered';
const LEVELS_AT = (rank) => ['thin', 'partial', 'covered'][Math.min(2, Math.max(0, rank))];
const nonEmpty = (s) => typeof s === 'string' && s.trim().length > 0;

/** Merge new facts into the ledger, skipping near-duplicates. */
export function addFacts(session, facts, now = 0) {
  if (!Array.isArray(facts) || !facts.length) return session;
  const seen = new Set(session.facts.map((f) => normalize(f.fact)));
  const added = [];
  for (const f of facts) {
    if (!f || !nonEmpty(f.fact)) continue;
    const key = normalize(f.fact);
    if (seen.has(key)) continue;
    seen.add(key);
    added.push({ dimension: f.dimension || null, fact: f.fact.trim() });
  }
  if (!added.length) return session;
  return bump(session, { facts: [...session.facts, ...added] }, now);
}
const normalize = (s) => String(s).toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();

/** The user told us to stop asking about this. Permanent, with an undo. */
export function waiveDimension(session, id, reason = null, now = 0) {
  return setStatus(session, id, 'waived', { waivedReason: reason }, now);
}
/** The user genuinely cannot know this yet. Stops counting against readiness. */
export function deferDimension(session, id, now = 0) {
  return setStatus(session, id, 'deferred', {}, now);
}
export function resumeDimension(session, id, now = 0) {
  return setStatus(session, id, 'probing', { waivedReason: null }, now);
}
function setStatus(session, id, status, extra, now) {
  getDimension(id);
  return bump(session, {
    coverage: { ...session.coverage, [id]: { ...session.coverage[id], status, ...extra } },
  }, now);
}

export function setPending(session, pending, now = 0) { return bump(session, { pending }, now); }
export function clearPending(session, now = 0) { return bump(session, { pending: null }, now); }
export function setZeroGainStreak(session, n, now = 0) { return bump(session, { zeroGainStreak: n }, now); }
export function setWrapOffered(session, v, now = 0) { return bump(session, { wrapOffered: v }, now); }
export function setTitle(session, title, now = 0) { return bump(session, { title }, now); }
export function setStatusField(session, status, now = 0) { return bump(session, { status }, now); }

export function setSynthesis(session, { text, tier = '', assumptions = [], openQuestions = null, now = 0 }) {
  const patch = {
    synthesis: { text, tier, at: now, stale: false, assumptions },
    status: 'done',
  };
  if (openQuestions) patch.openQuestions = openQuestions;
  return bump(session, patch, now);
}

/** Re-entry: a finished session that gains a turn has a stale synthesis. */
export function reopen(session, now = 0) {
  return bump(session, {
    status: 'interviewing',
    synthesis: { ...session.synthesis, stale: true },
    wrapOffered: false,
  }, now);
}

/** Forward-migrate a stored session. Unknown future schemas are rejected, not guessed at. */
export function migrate(stored) {
  if (!isRecord(stored)) return null;
  if (stored.schema > SCHEMA) return null;
  const base = createSession({ id: stored.id || 'recovered', now: stored.createdAt || 0 });
  const merged = { ...base, ...stored, schema: SCHEMA };
  merged.turns = recordArray(stored.turns).map((turn) => ({
    ...turn,
    chips: Array.isArray(turn.chips) ? turn.chips.filter((chip) => typeof chip === 'string') : [],
  }));
  merged.facts = recordArray(stored.facts).map((fact) => ({ ...fact }));
  merged.moveHistory = Array.isArray(stored.moveHistory)
    ? stored.moveHistory.filter((move) => typeof move === 'string')
    : [];
  merged.openQuestions = recordArray(stored.openQuestions).map((question) => ({ ...question }));
  merged.pending = isRecord(stored.pending) ? { ...stored.pending } : null;
  merged.coverage = { ...base.coverage };
  for (const id of DIMENSION_IDS) {
    if (isRecord(stored.coverage) && isRecord(stored.coverage[id])) {
      merged.coverage[id] = { ...base.coverage[id], ...stored.coverage[id] };
    }
  }
  const synthesis = isRecord(stored.synthesis) ? stored.synthesis : {};
  merged.synthesis = {
    ...base.synthesis,
    ...synthesis,
    assumptions: Array.isArray(synthesis.assumptions)
      ? synthesis.assumptions.filter((item) => typeof item === 'string')
      : [],
  };
  merged.meta = { ...base.meta, ...(isRecord(stored.meta) ? stored.meta : {}) };
  return merged;
}

/** The open turn, if one is awaiting an answer. */
export function openTurn(session) {
  const last = session.turns[session.turns.length - 1];
  return last && !last.answer && !last.skipped ? last : null;
}
export function answeredTurns(session) {
  return session.turns.filter((t) => t.answer || t.skipped);
}
